---
kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: eslint
  image: marcbachmann/eslint:5.16.0
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN

- name: install
  image: node:12
  commands: ["npm install"]

- name: test
  image: node:12
  commands: ["npm run test -s"]

- name: release
  image: livingdocs/semantic-release:v1.0.0
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN

trigger:
  event: [push]
---
kind: signature
hmac: eff159def7e807ca385481d60cde95f84b9fdbee02cc268a11b77a648f585dd8

...
