clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  npm-install:
    group: install
    image: node:10-alpine
    commands: ["npm install"]

  eslint:
    group: install
    image: marcbachmann/eslint:4.19.1
    secrets: [gh_token]

  test:
    group: test
    image: node:10-alpine
    commands: ["npm run test -s"]
